Legger til dialog.
navikt/sosialhjelp-test-proxy pull request #14
Opened 2021-04-13 06:43 UTC by perchrnie

2021-04-13 06:46 UTC, siljee requested changes

2021-04-13 06:46 UTC, siljee commented on default.conf
> +    location /sosialhjelp/dialof {
skriveleif :D

2021-04-13 06:47 UTC, siljee commented on default.conf
> +    location /sosialhjelp/dialof {
Mente du dialoff? 🍞

2021-04-13 06:48 UTC, siljee submitted a review, later dismissed

2021-04-13 06:48 UTC, perchrnie commented on default.conf
> +    location /sosialhjelp/dialof {
:-P

2021-04-13 06:48 UTC, siljee commented on default.conf
> +    location /sosialhjelp/dialof {
Hihi 😁

2021-04-15 06:43 UTC, siljee approved these changes

2021-04-15 06:49 UTC, merged